SELECT DISTINCT NAME,TEXT
FROM USER_SOURCE
WHERE TYPE = 'PROCEDURE'
AND UPPER(TEXT) LIKE '%SELECT%'
AND NAME NOT IN (
    SELECT DISTINCT NAME
    FROM USER_SOURCE
    WHERE TYPE = 'PROCEDURE'
    AND UPPER(TEXT) LIKE '%ORDER BY%'
);--ストアドプロシージャのソース内で、SELECT文が存在するが、ORDER BY句が存在しないパターン

